// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EditConstructionTableController from "./edit_construction_table_controller";
import VisualizerController from "./visualizer_controller";
import NewConstructionTableController from "./new_construction_table_controller"
import GraphicController from "./graphic_controller";

application.register("edit-construction-table", EditConstructionTableController)
application.register("visualizer", VisualizerController)
application.register("new-construction-table", NewConstructionTableController)
application.register("graphic-controller", GraphicController)
