Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Style/StringLiterals:
  Enabled: false