version: '3.5'

services:
  app:
    build: .
    command: "bin/dev"
    volumes:
      - .:/usr/src
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  postgresql:

networks:
  sapr_network:
    name: sapr