FROM ruby:3.1.2 AS build

# Install yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg -o /root/yarn-pubkey.gpg && apt-key add /root/yarn-pubkey.gpg
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install -y --no-install-recommends nodejs yarn

ENV APP_APTH=/usr/src
WORKDIR $APP_APTH
ENV PIDFILE=/dev/null

ADD Gemfile $APP_APTH/Gemfile
ADD Gemfile.lock $APP_APTH/Gemfile.lock

RUN rm -rf node_modules vendor
RUN gem install rails bundler
RUN bundle install
RUN yarn install
