version: '3.5'

services:
  app:
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && bin/dev"
    tty: true
    volumes:
      - .:/usr/src
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgresql:

networks:
  sapr_network:
    name: sapr